### ISSUE TITLE
Week 10 checklist backend

### ISSUE THREAD

**Issue by aaron-rub** [gigtieup/Python#1]
**11/1/2022 Week 10 To-do list** 

- [ ] Refine the API in the group flask project. 

- [x] Work on backend for sign-in page.

- [x] Work on backend for shopping-cart.

- [x] Check-in with group to exchange ideas and show progress.

- [x] Describe use of Lists or Dictionaries, database, tables, attributes, records, and systems of access (JSON, Lists, Dictionaries).

- [x] Prepare for Night of the museum on November 3rd.

- [x] Discuss group plan with Mort and get feedback from other students.
