### ISSUE TITLE
Week 10 Checklist - DevOps

### ISSUE THREAD

**Issue by yashakhoshini** [gigtieup/Python#2]
- [x] Check sites-available and sites-enabled for our repository
- [x] Make sure port and server name is accurate
- [x] Delete excess code that I added before from docker
- [ ] - [ ] Check API to make sure frontend and backend are clear
- [x] Curl localhost & sudo nano test
- [x] Restart nginx and check that website is up and running
- [x] Update website constantly by killing then re-building on AWS
- [x] Code logo so whenever it's clicked it goes to homepage
- [ ] Add & customize animations on website

[problems and solutions](https://yashakhoshini.github.io/yasha-fastpages/markdown/2022/10/28/problems-solutions.html)
