### ISSUE TITLE
Week 10 Checklist Frontend

### ISSUE THREAD

**Issue by jameshunter12** [gigtieup/Python#3]
- [x]  Figure out how add API to our website with html

- [x]  Work with sign in page and add to cart for easier customer interaction

- [x] Add things for easier customer interaction

- [x] Add new buttons to each product along with product names

- [x] Make sure the website is looking good and test new templates

- [ ] Get API to display on HTML page
